# Generated by Django 3.2.25 on 2024-05-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchefapp', '0002_auto_20240507_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
