# Generated by Django 3.2.25 on 2024-07-08 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchefapp', '0003_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='suma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='local',
            name='total_reviews',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
