# Generated by Django 3.2.25 on 2024-07-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchefapp', '0004_auto_20240708_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='avg_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
