# Generated by Django 3.2.25 on 2024-07-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buchefapp', '0006_auto_20240708_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local_category',
            name='user_id',
        ),
        migrations.AddField(
            model_name='local_category',
            name='category_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='buchefapp.category'),
            preserve_default=False,
        ),
    ]
