# Generated by Django 3.2.25 on 2024-07-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchefapp', '0009_rename_direction_local_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='local_image',
            field=models.ImageField(default='img/24/nophoto.jpg', upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
